### ISSUE TITLE
Apparently Wrong Result For 3D

### ISSUE THREAD

**Issue by NiteshBharadwaj** [lcosmo/isospectralization#4]
The constructed output cube for 3D using default code after 2000 iterations is protruding inwards instead of expected outwards.

Could you help replicate both 2D and 3D results from paper?

**Comment by salu133445** [comment]
By increasing the volume regularization to 1000 (`params.volume_reg = 1e3`), I succeeded to get the expected result. Perhaps you could also try setting it larger.
